version: 2
updates:
  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
    groups:
      backend-production:
        dependency-type: production
      backend-development:
        dependency-type: development
    open-pull-requests-limit: 5

  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: weekly
    groups:
      android-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
